export type RegistryType = "agent" | "skill" | "tool";
export type RiskTier = "T0" | "T1" | "T2" | "T3";
export type LifecycleState = "draft" | "pending_approval" | "approved" | "active" | "deprecated" | "retired" | "blocked";

export type RegistryObject = {
  id: string;
  type: RegistryType;
  name: string;
  version: string;
  description: string;
  owner: string;
  riskTier: RiskTier;
  lifecycleState: LifecycleState;
  environment: "dev" | "test" | "staging" | "prod";
  aiHarnessCertified: boolean;
  certificationEvidence: string;
  approvalState: "approved" | "pending" | "not_certified" | "blocked";
  sourcePath: string;
  dataClasses: string[];
  policies: string[];
  relationships: string[];
  inputs?: string[];
  outputs?: string[];
  sideEffects?: "read_only" | "reversible_write" | "irreversible_write";
  targetSystem?: string;
};

export const registryObjects: RegistryObject[] = [
  {
    id: "customer-service-agent",
    type: "agent",
    name: "Customer Service Agent",
    version: "0.1.0",
    description: "Fictional assisted-service agent for bounded customer-care journeys.",
    owner: "customer-care-platform",
    riskTier: "T2",
    lifecycleState: "active",
    environment: "test",
    aiHarnessCertified: true,
    certificationEvidence: "plan_change_eval_pack + plan_change_trajectory_checks",
    approvalState: "approved",
    sourcePath: "examples/telco-customer-care/agents/customer-service-agent.yaml",
    dataClasses: ["internal", "confidential"],
    policies: ["customer_data.access", "consent.required", "high_risk.action"],
    relationships: [
      "customer.change_plan",
      "customer.check_balance",
      "customer.replace_sim",
      "customer.read_limited_profile",
      "eligibility.check_plan_change",
      "billing.calculate_price_delta",
      "order.prepare_plan_change_request",
    ],
  },
  {
    id: "customer.change_plan",
    type: "skill",
    name: "Customer Plan Change",
    version: "0.1.0",
    description: "Reusable business capability for preparing a customer plan-change request.",
    owner: "customer-care-platform",
    riskTier: "T2",
    lifecycleState: "active",
    environment: "test",
    aiHarnessCertified: true,
    certificationEvidence: "Trajectory checks cover consent, policy gates, and tool sequence.",
    approvalState: "approved",
    sourcePath: "examples/telco-customer-care/skills/customer-change-plan.yaml",
    dataClasses: ["internal", "confidential"],
    policies: ["customer_data.access", "consent.required", "high_risk.action"],
    relationships: [
      "customer.read_limited_profile",
      "eligibility.check_plan_change",
      "billing.calculate_price_delta",
      "order.prepare_plan_change_request",
    ],
    inputs: ["customer_reference", "requested_plan_id", "channel"],
    outputs: ["eligibility_status", "price_delta_summary", "prepared_request_id"],
  },
  {
    id: "customer.check_balance",
    type: "skill",
    name: "Customer Balance Check",
    version: "0.1.0",
    description: "Read-only balance inquiry capability for customer-care assistants.",
    owner: "customer-care-platform",
    riskTier: "T1",
    lifecycleState: "active",
    environment: "test",
    aiHarnessCertified: true,
    certificationEvidence: "Read-only skill certification with customer data access policy.",
    approvalState: "approved",
    sourcePath: "examples/telco-customer-care/skills/customer-check-balance.yaml",
    dataClasses: ["confidential"],
    policies: ["customer_data.access"],
    relationships: ["customer.read_limited_profile"],
    inputs: ["customer_reference"],
    outputs: ["balance_summary"],
  },
  {
    id: "customer.replace_sim",
    type: "skill",
    name: "Customer SIM Replacement",
    version: "0.1.0",
    description: "Bounded SIM replacement capability with elevated oversight requirements.",
    owner: "customer-care-platform",
    riskTier: "T2",
    lifecycleState: "approved",
    environment: "test",
    aiHarnessCertified: true,
    certificationEvidence: "Approved for sample registry; runtime execution deferred.",
    approvalState: "approved",
    sourcePath: "examples/telco-customer-care/skills/customer-replace-sim.yaml",
    dataClasses: ["confidential"],
    policies: ["customer_data.access", "high_risk.action"],
    relationships: ["customer.read_limited_profile"],
    inputs: ["customer_reference", "replacement_reason"],
    outputs: ["replacement_case_reference"],
  },
  {
    id: "refund-iphone-device",
    type: "skill",
    name: "Refund iPhone Device",
    version: "0.0.1",
    description: "Uncertified example skill used to demonstrate a blocked refund path.",
    owner: "unknown",
    riskTier: "T3",
    lifecycleState: "blocked",
    environment: "test",
    aiHarnessCertified: false,
    certificationEvidence: "Missing registry approval, evaluation pack, and policy review.",
    approvalState: "not_certified",
    sourcePath: "demo-only/generated-scenario-d",
    dataClasses: ["confidential", "financial"],
    policies: ["certification-required-policy"],
    relationships: ["iphone-refund-issue-payment"],
    inputs: ["customer_reference", "device_identifier", "refund_reason"],
    outputs: ["refund_reference"],
  },
  {
    id: "customer.read_limited_profile",
    type: "tool",
    name: "Read Limited Customer Profile",
    version: "0.1.0",
    description: "Governed read-only access to limited fictional customer profile data.",
    owner: "customer-systems",
    riskTier: "T1",
    lifecycleState: "active",
    environment: "test",
    aiHarnessCertified: true,
    certificationEvidence: "Schema validated and bound to customer data access policy.",
    approvalState: "approved",
    sourcePath: "examples/telco-customer-care/tools/customer-read-limited-profile.yaml",
    dataClasses: ["confidential"],
    policies: ["customer_data.access"],
    relationships: ["fictional-crm-system", "customer.change_plan", "customer.check_balance"],
    sideEffects: "read_only",
    targetSystem: "fictional-crm-system",
    inputs: ["customer_reference"],
    outputs: ["current_plan_id", "customer_reference", "account_status"],
  },
  {
    id: "eligibility.check_plan_change",
    type: "tool",
    name: "Check Plan Eligibility",
    version: "0.1.0",
    description: "Checks whether a fictional customer can move to a requested plan.",
    owner: "product-platform",
    riskTier: "T2",
    lifecycleState: "active",
    environment: "test",
    aiHarnessCertified: true,
    certificationEvidence: "Mock tool adapter covered by telco journey validation.",
    approvalState: "approved",
    sourcePath: "examples/telco-customer-care/tools/eligibility-check-plan-change.yaml",
    dataClasses: ["internal", "confidential"],
    policies: ["customer_data.access"],
    relationships: ["fictional-product-catalogue-system", "customer.change_plan"],
    sideEffects: "read_only",
    targetSystem: "fictional-product-catalogue-system",
    inputs: ["customer_reference", "requested_plan_id"],
    outputs: ["eligibility_status", "eligibility_reason"],
  },
  {
    id: "billing.calculate_price_delta",
    type: "tool",
    name: "Calculate Price Delta",
    version: "0.1.0",
    description: "Calculates fictional monthly price difference for the requested plan change.",
    owner: "billing-platform",
    riskTier: "T2",
    lifecycleState: "active",
    environment: "test",
    aiHarnessCertified: true,
    certificationEvidence: "Schema validated and restricted to read-only billing calculation.",
    approvalState: "approved",
    sourcePath: "examples/telco-customer-care/tools/billing-calculate-price-delta.yaml",
    dataClasses: ["confidential"],
    policies: ["consent.required"],
    relationships: ["fictional-billing-system", "customer.change_plan"],
    sideEffects: "read_only",
    targetSystem: "fictional-billing-system",
    inputs: ["current_plan_id", "requested_plan_id"],
    outputs: ["monthly_price_delta", "effective_date"],
  },
  {
    id: "order.prepare_plan_change_request",
    type: "tool",
    name: "Prepare Plan-Change Request",
    version: "0.1.0",
    description: "Prepares but does not submit a fictional plan-change request.",
    owner: "order-platform",
    riskTier: "T2",
    lifecycleState: "active",
    environment: "test",
    aiHarnessCertified: true,
    certificationEvidence: "Reversible-write tool approved for request preparation only.",
    approvalState: "approved",
    sourcePath: "examples/telco-customer-care/tools/order-prepare-plan-change-request.yaml",
    dataClasses: ["internal", "confidential"],
    policies: ["consent.required", "high_risk.action"],
    relationships: ["fictional-order-system", "customer.change_plan"],
    sideEffects: "reversible_write",
    targetSystem: "fictional-order-system",
    inputs: ["customer_reference", "requested_plan_id", "approval_reference"],
    outputs: ["prepared_request_id", "prepared_request_status"],
  },
  {
    id: "iphone-refund-issue-payment",
    type: "tool",
    name: "Issue iPhone Refund",
    version: "0.0.1",
    description: "Uncertified irreversible refund tool used to demonstrate governance blocking.",
    owner: "unknown",
    riskTier: "T3",
    lifecycleState: "blocked",
    environment: "test",
    aiHarnessCertified: false,
    certificationEvidence: "Missing owner, policy approval, evaluation pack, and audit obligation.",
    approvalState: "blocked",
    sourcePath: "demo-only/generated-scenario-d",
    dataClasses: ["confidential", "financial"],
    policies: ["certification-required-policy"],
    relationships: ["refund-iphone-device"],
    sideEffects: "irreversible_write",
    targetSystem: "unknown-refund-system",
    inputs: ["customer_reference", "device_identifier", "refund_amount"],
    outputs: ["refund_reference", "financial_adjustment_id"],
  },
];
